export default {
  light: {
    text: "#000",
    textField: "#000",
    orangeButtonIcon: "#fff",
    textPlaceholder: "#ccc",
    background: "#faf3f3",
    tint: "#5D5CE7",
    tintInactive: "#5f7587",
    calendarPanel: "#e9f0fd",
    calendarTitle: "#3265cb",
    calendarDayTextColor: "#2d4150",
    textDisabledColor: "#2d4150",
    projectPanel: "#e9f0fd",
    dots: "#ccc",
    dotsActive: "#3265cb",
    bigCalendarBoxes: "#dcdcdd",
    bigCalendarDayNumberInactive: "#2d4150",
    bigCalendarActive: "#3265cb",
    bigCalendarContrastText: "#fff",
    skeletonBackground: "#e1e1e1",
    bubbleBackgroundColorMe: "#057EFD",
    bubbleBackgroundColorOther: "#e9f0fd",
    bubbleTextColorMe: "#fff",
    bubbleTextColorOther: "#000",
    postBackground: "#fff",
    button: "##f97316",
  },
  dark: {
    text: "#fff",
    textField: "#000",
    orangeButtonIcon: "#000",
    textPlaceholder: "#ccc",
    background: "#101411",
    tint: "#5D5CE7",
    tintInactive: "#5d6f7c",
    calendarPanel: "#2f95dc",
    calendarTitle: "#fff",
    calendarDayTextColor: "#fff",
    textDisabledColor: "#fff",
    projectPanel: "#232323",
    dots: "#e9f0fd",
    dotsActive: "#3265cb",
    bigCalendarBoxes: "#2d4150",
    bigCalendarDayNumberInactive: "#e9f0fd",
    bigCalendarActive: "#3265cb",
    bigCalendarContrastText: "#fff",
    skeletonBackground: "#2d4150",
    bubbleBackgroundColorMe: "#057EFD",
    bubbleBackgroundColorOther: "#53425A",
    bubbleTextColorMe: "#fff",
    bubbleTextColorOther: "#fff",
    postBackground: "#373544",
    button: "##f97316",
  },
};

export const blurhash =
  "|rF?hV%2WCj[ayj[a|j[az_NaeWBj@ayfRayfQfQM{M|azj[azf6fQfQfQIpWXofj[ayj[j[fQayWCoeoeaya}j[ayfQa{oLj?j[WVj[ayayj[fQoff7azayj[ayj[j[ayofayayayj[fQj[ayayj[ayfjj[j[ayjuayj[";
