name: update_codepush_www
on:
  workflow_dispatch:
  push:
    branches:
      - appstore
jobs:
  update:
    name: update_codepush
    runs-on: ubuntu-latest
    steps:
      - name: Check for EXPO_TOKEN
        run: |
          if [ -z "${{ secrets.EXPO_TOKEN }}" ]; then
            echo "You must provide an EXPO_TOKEN secret linked to this project's Expo account in this repo's secrets. Learn more: https://docs.expo.dev/eas-update/github-actions"
            exit 1
          fi

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: yarn

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: yarn install

      - name: EAS Apply codepush
        run: eas update --branch production --message "Github Action Updating the app"

      - name: Deploy to WWW Hosting
        run: yarn predeploy

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_BUILDER_403D5 }}"
          channelId: live
          projectId: builder-403d5
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
